#!/bin/sh

# Under CI, there are two CPUs, but limit to 1 to avoid out-of-memory error.
if [ -n "$(./is-ci.sh)" ]; then
  num_jobs=1
else
  num_jobs="$(nproc || sysctl -n hw.ncpu || getconf _NPROCESSORS_ONLN || echo 1)"
fi
make -k style-check --jobs="${num_jobs}"
