name: Check code style

on: [push, pull_request]   # yamllint disable-line rule:truthy

jobs:
  style-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          show-progress: false
      - name: Install markdownlint-cli2
        run: |
          sudo apt-get -qqy install npm
          npm install --quiet markdownlint-cli2 --global
      - name: Install shfmt
        run: sudo apt-get -qyy install shfmt
      - name: make showvars
        run: make showvars
      - name: make style-check
        run: make style-check
