#!/bin/sh

# Under CI, there are two CPUs, but limit to 1 to avoid out-of-memory error.
if [ -n "$("${PLUME_SCRIPTS:-.plume-scripts}"/is-ci.sh)" ]; then
  num_jobs=1
elif [ command -v nproc > /dev/null 2>&1 ]; then
  num_jobs="$(nproc)"
else
  num_jobs="$(sysctl -n hw.ncpu || getconf _NPROCESSORS_ONLN || echo 1)"
fi
make -k style-check --jobs="${num_jobs}"
