#!/bin/sh

# Sets environment variables COMMIT_RANGE, BRANCH, and STRIP_LINT, when run
# in a pull request under Azure Pipelines, CircleCI, or Travis CI.

# You must run this via `source git-set-commit-range` (run in same shell),
# not via `git-set-commit-range` (run it its own subshell).

# If it's a pull request, set COMMIT_RANGE and BRANCH
if [ -n "$SYSTEM_PULLREQUEST_TARGETBRANCH" ] ; then
  ## Azure Pipelines
  COMMIT_RANGE=`git rev-parse HEAD^1`...$BUILD_SOURCEVERSION
  BRANCH=$SYSTEM_PULLREQUEST_TARGETBRANCH
  STRIP_LINT=4
elif [ -n "$TRAVIS_COMMIT_RANGE" ] ; then
  ## Travis CI
  # $TRAVIS_COMMIT_RANGE is empty for builds triggered by the initial commit of a new branch.
  # Until https://github.com/travis-ci/travis-ci/issues/4596 is fixed, $TRAVIS_COMMIT_RANGE is a
  # good argument to `git diff` but a bad argument to `git log` (they interpret "..." differently!).
  COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
  BRANCH=$CIRCLE_BRANCH
  STRIP_LINT=2
elif [ -n "$CIRCLE_COMPARE_URL" ] ; then
  ## CircleCI
  COMMIT_RANGE=$(echo "${CIRCLE_COMPARE_URL}" | cut -d/ -f7)
  if [[ $COMMIT_RANGE != *"..."* ]]; then
    COMMIT_RANGE="${COMMIT_RANGE}...${COMMIT_RANGE}"
  fi
  BRANCH=$TRAVIS_BRANCH
  # TODO: determine correct value
  STRIP_LINT=2
fi
