#!/bin/sh

## This script is obsolete.  Use ci-info instead.

# Returns the organization of the current git clone, like "plume-lib" for a
# clone of this repository.  Contains special code to handle pull requests in
# Travis and Azure Pipelines.
# If an argument is passed in, it is used as a default if no owner can be determined.

## Continuous integration services
if [ "$TRAVIS" = "true" ]; then
  SLUGOWNER=${TRAVIS_PULL_REQUEST_SLUG%/*}
  if [ "$SLUGOWNER" = "" ]; then
    SLUGOWNER=${TRAVIS_REPO_SLUG%/*}
  fi
elif [ -n "$AZURE_HTTP_USER_AGENT" ]; then
  SLUG=`wget -q -O - https://api.github.com/repos/${BUILD_REPOSITORY_NAME}/pulls/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER} | jq .head.label | sed 's/"//g'`
  SLUGOWNER=${SLUG%:*}
  SLUGREPO=${SLUG#*:}
fi

## Git clone
if [ "$SLUGOWNER" = "" ]; then
  URL=`git config --get remote.origin.url`
  SLUG=${URL#*:}
  SLUGOWNER=${SLUG%/*}
fi

## Default
if [ "$SLUGOWNER" = "" ]; then
  SLUGOWNER=$1
fi

echo $SLUGOWNER
