#!/bin/sh

# find-git-branch:  tests whether a branch exists in a Git repository;
#   prints the branch, or prints "master" if the branch does not exist.
# Usage:  find-git-branch REPO BRANCH
# Prints either BRANCH, if it exists in REPO, or else "master".

# For example usage within a Travis build, see
# https://github.com/plume-lib/plume-scripts#usage-of-git-find-forkbranch

if [ "$#" -eq 1 ]; then
    script=$(basename -- "$0")
    >&2 echo "Warning: $script requires 2 arguments, got $#"
    >&2 echo "Usage: $script REPO BRANCH"
    >&2 echo "Returning \"master\""
    echo "master"
    exit 0
fi

REPO=$1
BRANCH=$2

if (git ls-remote --quiet --exit-code --heads ${REPO} ${BRANCH} > /dev/null) ; then
  echo ${BRANCH}
else
  echo "master"
fi
