#!/bin/sh

## This script is obsolete.
## Use `ci-info`, which is also in this directory.

# Sets environment variables COMMIT_RANGE, BRANCH, and STRIP_LINT, when run
# in a pull request under Azure Pipelines, CircleCI, or Travis CI.
# Use it like this:
#   source /path/to/git-set-commit-range
# (Don't just run `/path/to/git-set-commit-range`, which would run it
# its own subshell rather than in the same shell.)

# For typical use, see comments in file `lint-diff.py` in this directory.

# If it's a pull request, set COMMIT_RANGE and BRANCH
if [ -n "$SYSTEM_PULLREQUEST_TARGETBRANCH" ] ; then
  ## Azure Pipelines
  COMMIT_RANGE=`git rev-parse HEAD^1`...$BUILD_SOURCEVERSION
  BRANCH=$SYSTEM_PULLREQUEST_TARGETBRANCH
  STRIP_LINT=4
elif [ -n "$TRAVIS_COMMIT_RANGE" ] ; then
  ## Travis CI
  COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
  BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  STRIP_LINT=2
elif [ -n "$CIRCLE_COMPARE_URL" ] ; then
  ## CircleCI
  COMMIT_RANGE=$(echo "${CIRCLE_COMPARE_URL}" | cut -d/ -f7)
  if [ $COMMIT_RANGE != *"..."* ]; then
    COMMIT_RANGE="${COMMIT_RANGE}...${COMMIT_RANGE}"
  fi
  BRANCH=$CIRCLE_BRANCH
  # TODO: determine correct value
  STRIP_LINT=2
fi
