#!/usr/bin/env python
"""Exits with failure message if, for any single class, coverage goes down.

Arguments: two Jacoco coverage reports (.csv files).
"""

# import argparse
import csv
import sys
from pathlib import Path

PROGRAM = Path(__file__).name

DEBUG = False

if len(sys.argv) != 3:
    print(PROGRAM + "received " + (len(sys.argv) - 1) + "arguments, expected 2: " + sys.argv)
    sys.exit(2)


def read_jacoco_csv_to_map(filename: str) -> map[str, tuple[int, int]]:
    """Read a Jacoco file.

    Returns:
        a map from class name to (line_missed, line_covered).
    """
    result = {}
    with Path.open(filename) as csvfile:
        dict_reader = csv.DictReader(csvfile)
        for row in dict_reader:
            fq_classname = row["PACKAGE"] + row["CLASS"]
            result[fq_classname] = (row["LINE_MISSED"], row["LINE_COVERED"])
    return result


def coverage_ratio(coverage_pair: tuple[int, int]) -> float:
    """Return the coverage ratio for the given (missed, covered) tuple.

    Returns:
        the coverage ratio for the given (missed, covered) tuple.
    """
    missed = coverage_pair[0]
    covered = coverage_pair[1]
    ratio = covered / (covered + missed)
    return ratio


# Example usage (assuming a file named 'data.csv' exists with headers)
# read_csv_as_dicts('data.csv')

old_coverage = read_jacoco_csv_to_map(sys.argv[1])
new_coverage = read_jacoco_csv_to_map(sys.argv[2])

for fq_classname, new_line_cov in sorted(new_coverage.items()):
    failed = False
    old_line_cov = new_coverage[fq_classname]
    if old_line_cov is None:
        continue
    old_ratio = coverage_ratio(old_line_cov)
    new_ratio = coverage_ratio(new_line_cov)
    if new_ratio < old_ratio:
        failed = True
        print("Coverage of", fq_classname, "fell from", old_ratio, "to", new_ratio)

if failed:
    sys.exit(1)
