#!/usr/bin/env perl

# Shorten a path environment variable by removing duplicates and
# non-existent directories.
# With optional argument "-r REGEXP", removes any matching path element.
# Works for either space- or colon-delimited paths.
# Usage:
#   # csh
#   setenv PATH `echo $PATH | .../plume-scripts/path-remove`
#   # sh
#   export PATH=`echo $PATH | .../plume-scripts/path-remove`
#   ## Does this even work??
#   set path = (`echo $path | .../plume-scripts/path-remove`)

my $debug = 0;
# $debug = 1;

my $extra_regexp;               # undefined if not specified on command line.

while (scalar(@ARGV) > 0) {
  if ($ARGV[0] eq "-r") {
    if (scalar(@ARGV) < 2) {
      die "No regexp specified after -r";
    }
    shift @ARGV;
    $extra_regexp = shift @ARGV;
  } else {
    die "path-remove: Unrecognized argument $ARGV[0]";
  }
}

# The separator for the output.  All the input lines are merged into a single
# output path, so the separator is decided once, by the first input line that
# contains one; later lines do not change it.  (Each line is still split
# according to its own contents.)  The default matters only if no input line
# contains a separator.
$splitchar = ":";
$splitchar_known = 0;
@result = ();
while (<>) {
      my @pieces;
      chomp;
      if ($_ =~ /:/) {
	@pieces = split(":");
	if (! $splitchar_known) { $splitchar = ":"; $splitchar_known = 1; }
      } elsif ($_ =~ / /) {
	@pieces = split(" ");
	if (! $splitchar_known) { $splitchar = " "; $splitchar_known = 1; }
      } else {
	# no separators; assume colon, but don't set splitchar.
	@pieces = split(":");
      }
      if ($debug) {
	print STDERR "splitchar: $splitchar\n";
	print STDERR "" . scalar(@pieces) . " initial components\n";
	# print STDERR "Input: $_\n";
      }
      foreach $temp (@pieces) {
	if (! -d $temp) { next; }
	if (defined($already_seen{$temp})) { next; }
        if (defined($extra_regexp) && ($temp =~ /$extra_regexp/)) { next; }
        # This directory should appear in the output
        push(@result, $temp);
        $already_seen{$temp} = 1;
      }
}

if ($debug) {
  print STDERR "" . scalar(@result) . " final components\n";
}

print join($splitchar, @result);
