test:
	${MAKE} -C jacoco-coverage-ratchet-test test
	${MAKE} -C lint-diff-test test
	${MAKE} -C sort-compiler-output-test test
	${MAKE} -C sort-directory-order-test test

clean:
	${MAKE} -C jacoco-coverage-ratchet-test clean
	${MAKE} -C lint-diff-test clean
	${MAKE} -C sort-compiler-output-test clean
	${MAKE} -C sort-directory-order-test clean
